dataset:
  exp: ACDC_semi
  subset_name:
  dimension: 3D
  num_classes: 4
  label_list: [0,1,2,3]
#  root_dir: /home/lu/HeSH/datasets/ACDC/ACDC
  root_dir: /data/heshihuan/datasets/ACDC

  in_channels: 1
  kwargs:
    labeled_num: 14
    labeled_bs: 8
    batch_size: 16
    batch_size_val: 1
    num_workers: 16
    resize_size: [256 , 256]

network:
  net_type: unet_slc
  model2_inchns: 5
  ema_decay: 0.99
lr:
  base_lr: 0.05

#lr:
#  base_lr: 0.01 #源码的base_lr=0.01

loss:
  consistency: 0.01
  consistency_rampup: 1000.0  #源码是200

  block_num: 4
  use_block_dice_loss: true

save:
  val_interval: 100
  max_iterations: 20000
  cur_program_log_root: null

logging:
  logfile_level: info
  stdout_level: info
  log_file: info_
  log_format: '%(asctime)s %(levelname)-7s %(message)s'
  rewrite: true
  log_to_file:




