dataset:
  exp: BUSI_original_semi
  dimension: 2D
  num_classes: 2
  label_list:
  - 0
  - 1
  root_dir: /data/heshihuan/datasets/BUSI/train_val_test_256X256_7_1_2
  in_channels: 1
  kwargs:
    labeled_num: 0.4
    labeled_bs: 8
    batch_size: 16
    batch_size_val: 1
    num_workers: 16
    resize_size:
    - 224
    - 224
  noise_std: 0.1
  ignore_label: -1
network:
  net_type: unet_ppcn_difficulity_sdf_cnn_tf3
  backbone: resnet34
  download_patch: 4
  embed_dim: 36
  fuse_dim: 128
  contrast_index: -1
  ema_decay: 0.99
  aux_loss:
    ndim: 256
    loss_weight: 0.4
  decoder:
    type: decoder_deeplabv3_plus
    kwargs:
      inner_planes: 256
      dilations:
      - 12
      - 24
      - 36
      low_conv_in: 32
      low_conv_out: 128
      seg_head_out_dim: 128
lr:
  base_lr: 0.05
loss:
  consistency: 0.01
  consistency_rampup: 1000.0
save:
  val_interval: 100
  max_iterations: 20000
  cur_program_log_root: null
logging:
  logfile_level: info
  stdout_level: info
  log_file: info_
  log_format: '%(asctime)s %(levelname)-7s %(message)s'
  rewrite: true
  log_to_file: null
criterion:
  type: ohem
  kwargs:
    thresh: 0.7
    min_kept: 100000
