dataset:
  exp: breast_MRI_augmerge_1674_semi
  subset_name: null
  dimension: 2D
  num_classes: 2
  label_list:
  - 0
  - 1
  root_dir: /data/heshihuan/datasets/BML_cropresize_1674/merge_modality_tr_val_test_7_1_2
  in_channels: 1
  kwargs:
    labeled_num: 0.6
    labeled_bs: 8
    batch_size: 16
    batch_size_val: 1
    num_workers: 16
    resize_size:
    - 256
    - 256
network:
  net_type: unet_pccs
  ema_net_type: unet_pccs_ema
  ema_alpha: 0.99
  momentum_fromlearn: 0.999
lr:
  base_lr: 0.05
loss:
  consistency: 0.01
  consistency_rampup: 1000.0
  auxce_coefficient: 0.3
  contra_coefficient: 0.01
  uncertainty_coefficient: 0.1
contras:
  is_queue: false
  getq_step: 200
  max_queue_num: 256
  divide_proto_num: 3
  temperature: 0.05
  begin_contra: 8
  end_contra: 16
protoseg:
  gamma: 0.999
  num_prototype: 2
  update_prototype: true
save:
  val_interval: 100
  max_iterations: 20000
  cur_program_log_root: null
logging:
  logfile_level: info
  stdout_level: info
  log_file: info_
  log_format: '%(asctime)s %(levelname)-7s %(message)s'
  rewrite: true
  log_to_file: null
